version: 1.0.{build}

platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: cmake --version

build_script:
  - cmd: cd libskeleton
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. --build missing
  - cmd: cmake .. -G "Visual Studio 16"
  - cmd: cmake --build . --config Release --parallel 2
  - cmd: ctest --parallel 2
  - cmd: cmake --install .
  - cmd: cd ../../consumer/
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16"
  - cmd: cmake --build . --config Release --parallel 2

test_script:
  - cmd: cd Release
  - cmd: skeletonconsumer
